# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-19 07:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiSubscription', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='asx_code',
            field=models.CharField(default='', max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='frequency',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
