# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-20 01:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiSubscription', '0002_auto_20160419_0709'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='ownerUser',
        ),
        migrations.RemoveField(
            model_name='event',
            name='title',
        ),
        migrations.AddField(
            model_name='event',
            name='ownerEmail',
            field=models.EmailField(default='', max_length=254),
            preserve_default=False,
        ),
    ]
